name: task_manager
description: "A task manager app created with flutter, firebase and local storage."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  fluttertoast: ^8.2.4
  hive_flutter: ^1.1.0
  lottie: ^2.7.0
  uuid: ^4.2.2
  flutter_slidable: ^3.0.1
  go_router: ^13.0.0
  internet_connection_checker_plus: ^2.1.0
  dynamic_color: ^1.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    # - assets/images/
